### ISSUE TITLE
deleting a tiddler via the api leads to an error

### ISSUE THREAD

**Issue by cdent** [cdent/tank#141]
I delete the tiddler associated with https://tank.peermore.com/tanks/cdent/foo and then trying to re-GET it I get:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/httpexceptor/__init__.py", line 62, in __call__
    return self.application(environ, start_response)
  File "/home/cdent/src/tank/tiddlywebplugins/tank/httperror.py", line 25, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tiddlyweb/web/wsgi.py", line 190, in __call__
    output = self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tiddlyweb/web/serve.py", line 161, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tiddlyweb/web/serve.py", line 117, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tiddlyweb/web/query.py", line 44, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tiddlyweb/web/wsgi.py", line 128, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tiddlyweb/web/extractor.py", line 34, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tiddlyweb/web/wsgi.py", line 38, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tiddlyweb/web/negotiate.py", line 30, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tiddlywebplugins/cors.py", line 87, in __call__
    return self.application(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/tiddlywebplugins/csrf.py", line 79, in __call__
    return app()
  File "/usr/local/lib/python2.7/dist-packages/tiddlywebplugins/csrf.py", line 75, in app
    output = self.application(environ, fake_start_response)
  File "/usr/local/lib/python2.7/dist-packages/selector.py", line 137, in __call__
    return app(environ, start_response)
  File "/home/cdent/src/tank/tiddlywebplugins/tank/wiki.py", line 130, in wiki_page
    stiddler.bag) for stiddler in sisterlinks]))
  File "/home/cdent/src/tank/tiddlywebplugins/tank/search.py", line 88, in get_tiddlers_from_search
    bag = store.get(Bag(bag))
  File "/usr/local/lib/python2.7/dist-packages/tiddlyweb/store.py", line 196, in get
    thing = func(thing)
  File "/usr/local/lib/python2.7/dist-packages/tiddlywebplugins/caching.py", line 184, in bag_get
    bag = self.cached_storage.bag_get(bag)
  File "/usr/local/lib/python2.7/dist-packages/tiddlywebplugins/devstore2.py", line 77, in bag_get
    return self.wrapped_storage.bag_get(bag)
  File "/usr/local/lib/python2.7/dist-packages/tiddlyweb/stores/text.py", line 147, in bag_get
    (bag_path, exc))
NoBagError: unable to read policy or description at /home/cdent/tiddlywebs/tank.peermore.com/store/bags/wikicorstest: [Errno 2] No such file or directory: '/home/cdent/tiddlywebs/tank.peermore.com/store/bags/wikicorstest/policy'
```

**Comment by cdent** [comment]
Getting the tiddler directly at https://tank.peermore.com/bags/cdent/tiddlers/foo gets the expected 404
